[package]
name = "winter-heart"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
humantime = "2.2.0"
poise = "0.6.1"
serenity = { version = "0.12.4", features = ["model", "cache"] }
tokio = { version = "1.45.1", features = ["full"] }
